# Site settings
title: Kate Welsh Ceramics
email: kate@kwceramics.ca
formspree: f/xnqejlno # form ID from https://formspree.io/forms/
url: https://www.kwceramics.ca
description: "Local pottery and ceramics by artist Kate Welsh. Based out of Kitchener-Waterloo, Ontario, Canada."
keywords: "pottery,ceramics,clay,mugs,bowls,cups,local,artist,kitchener,waterloo,canada"
skills: "Ceramicist"
meta_author: Welsh Kate

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color reference only; not actually used :(
color:
  primary: 454d3c
  primary-highlight: 60704e
  secondary: f8f7f2
  secondary-dark: c0beb3

# Footer settings
footer:
  copyright: Kate Welsh Ceramics
  location: Location
  social: Social
  credits: Associations

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/katewelshceramics

# Postal address (add as many lines as necessary)
address:
  - line: Waterloo, Ontario, Canada

# Credits content
credits: '<a href="https://www.waterloopotters.ca/">Waterloo Potters Workshop</a>'

# Build settings
markdown: kramdown
permalink: pretty
