# Site settings
title: kwceramics
email: kate@kwceramics.ca
url: https://www.kwceramics.ca
description: "Local pottery and ceramics by artist Kate Welsh based out of Kitchener-Waterloo."
keywords: "pottery,ceramics,clay,mugs,bowls,cups,local,artist,kitchener,waterloo,canada"
skills: "Ceramicist"
meta_author: Welsh Kate

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - comment the line below if you want to stick with the default PHP contact form
contact: static


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Kate Welsh
  location: Canada
  social: todo:insta
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:
  - title: ins
    url: todo
  - title: github
    url: http://github.com/vincentvandough

# Postal address (add as many lines as necessary)
address:
  - line: Kitchener, ON

# Credits content
credits: 'todo: waterloo potters guild'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
