# Site settings
title: kw ceramics
email: kate@kwceramics.ca
url: https://www.kwceramics.ca
description: "Local pottery and ceramics by artist Kate Welsh based out of Kitchener-Waterloo."
keywords: "pottery,ceramics,clay,mugs,bowls,cups,local,artist,kitchener,waterloo,canada"
skills: "Ceramicist"
meta_author: Welsh Kate

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 454d3c #80B3FF
  primary-highlight: 60704e
  secondary: f8f7f2 #2c3e50 #FD6E8A
  secondary-dark: d8d6ca #A2122F

# Footer settings
footer:
  copyright: Kate Welsh Ceramics
  location: Location
  social: Social
  credits: Associations

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/katewelshceramics

# Postal address (add as many lines as necessary)
address:
  - line: Kitchener, ON

# Credits content
credits: '<a href="https://www.waterloopotters.ca/">Waterloo Potters Workshop</a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
